<a href="https://colab.research.google.com/github/juyounLee/MathExercise/blob/main/Linear_alg_Ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# column vector

c = np.array([1, 2, 3])
print(c.shape)

# obtaining a particular entry
print(c[0])

(3,)
1


In [4]:
# row vector

r = np.array([[1, 2, 3]])
print(r.shape)

# obtain a particular entry
print(r[0][2])

(1, 3)
3


In [5]:
# creating a matrix with all zeros
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [6]:
# creating a matrix with all ones
b = np.ones(3)
print(b)

[1. 1. 1.]


In [8]:
# creating a matrix with random value
d = np.random.random((2, 3))
print(d)

[[0.2882983  0.44758152 0.63328671]
 [0.14126639 0.78060589 0.14183581]]


In [9]:
# creating a matrix
A = np.array([[1,2], [3,4], [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
B = np.array([[11,12,13,14],[15,16,17,18]])
print(B)

[[11 12 13 14]
 [15 16 17 18]]


In [12]:
# transpose a matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [13]:
# matrix-matrix multiplication
np.dot(A, B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [14]:
# coefficient matrix A and a vector b
A = np.array([[60,5.5,1], [65,5.0,0], [55,6.0,1]])
b = np.array([66, 70, 78])

In [15]:
# compute an inverse
from numpy.linalg import inv

A_inv = inv(A)
print(A_inv)

[[ 0.08695652  0.00869565 -0.08695652]
 [-1.13043478  0.08695652  1.13043478]
 [ 2.         -1.         -1.        ]]


In [18]:
# identity matrix
i1 = np.dot(A, A_inv)
i2 = np.dot(A_inv, A)
print(i1)
print(i2)

[[ 1.0000000e+00  0.0000000e+00 -4.4408921e-16]
 [ 8.8817842e-16  1.0000000e+00 -8.8817842e-16]
 [-8.8817842e-16  0.0000000e+00  1.0000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-7.99360578e-15  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [17]:
answer = np.dot(A_inv, b)
print(answer)

[ -0.43478261  19.65217391 -16.        ]


In [19]:
# a better way to solve the same linear system
from numpy.linalg import solve

answer1 = solve(A, b)
answer1

array([ -0.43478261,  19.65217391, -16.        ])